version = 0.1

[default]

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "cloudfront-continuous-deployment-workflow-dev"
s3_bucket = "YOUR_S3_BUCKET_NAME"
s3_prefix = "cloudfront-continuous-deployment-workflow/dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = ["Environment=dev"]
