AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.11

  SAM Template for cloudfront-continuous-deployment-stepfunctions

Globals:
  Function:
    Runtime: python3.11
    Handler: app.lambda_handler
    Timeout: 180

Parameters:
  ResourcePrefix:
    Type: String
    Default: cfcd

Resources:
  CloudFrontContinuousDeploymentStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${ResourcePrefix}-statemachine
      Role: !GetAtt CloudFrontContinuousDeploymentStateMachineExecutionRole.Arn
      DefinitionUri: statemachine/workflow.asl.json
      DefinitionSubstitutions:
        CreateStagingDistributionFunctionArn: !GetAtt CreateStagingDistributionFunction.Arn
        StatusCheckFunctionArn: !GetAtt StatusCheckFunction.Arn
        TestDistributionFunctionArn: !GetAtt TestDistributionFunction.Arn
        PromoteDistributionFunctionArn: !GetAtt PromoteDistributionFunction.Arn
        DetachContinuousDeploymentPolicyFunctionArn: !GetAtt DetachContinuousDeploymentPolicyFunction.Arn
        DisableStagingDistributionFunctionArn: !GetAtt DisableStagingDistributionFunction.Arn
        DeleteStagingDistributionFunctionArn: !GetAtt DeleteStagingDistributionFunction.Arn

  CloudFrontContinuousDeploymentStateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ResourcePrefix}-statemachine-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StateMachineExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:invokeFunction
                Resource:
                  - !GetAtt CreateStagingDistributionFunction.Arn
                  - !GetAtt StatusCheckFunction.Arn
                  - !GetAtt TestDistributionFunction.Arn
                  - !GetAtt PromoteDistributionFunction.Arn
                  - !GetAtt DetachContinuousDeploymentPolicyFunction.Arn
                  - !GetAtt DisableStagingDistributionFunction.Arn
                  - !GetAtt DeleteStagingDistributionFunction.Arn

  CreateStagingDistributionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-create-staging-distribution-function
      CodeUri: functions/create_staging_distribution
      Role: !GetAtt LambdaExecutionRole.Arn

  StatusCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-status-check-function
      CodeUri: functions/status_check
      Role: !GetAtt LambdaExecutionRole.Arn

  TestDistributionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-test-distribution-function
      CodeUri: functions/test_distribution
      Role: !GetAtt LambdaExecutionRole.Arn

  PromoteDistributionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-promote-distribution-function
      CodeUri: functions/promote_distribution
      Role: !GetAtt LambdaExecutionRole.Arn

  DetachContinuousDeploymentPolicyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-detach-continuous-deployment-policy-function
      CodeUri: functions/detach_continuous_deployment_policy
      Role: !GetAtt LambdaExecutionRole.Arn

  DisableStagingDistributionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-disable-staging-distribution-function
      CodeUri: functions/disable_staging_distribution
      Role: !GetAtt LambdaExecutionRole.Arn

  DeleteStagingDistributionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-delete-staging-distribution-function
      CodeUri: functions/delete_staging_distribution
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ResourcePrefix}-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudfront:CopyDistribution
                  - cloudfront:CreateContinuousDeploymentPolicy
                  - cloudfront:CreateDistribution
                  - cloudfront:DeleteContinuousDeploymentPolicy
                  - cloudfront:DeleteDistribution
                  - cloudfront:GetContinuousDeploymentPolicyConfig
                  - cloudfront:GetDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:UpdateContinuousDeploymentPolicy
                  - cloudfront:UpdateDistribution
                Resource: "*"
