name: build

on: [push]

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install --upgrade pip && pip install poetry
      - name: Install packages
        run: poetry install --no-interaction --with dev
      - name: Run test
        run: poetry run cfn-lint --template template.yaml
      - name: Run build
        uses: aws-actions/setup-sam@v2
        run: sam build --use-container
